### PR TITLE
[JENKINS-40627] Check that we show emtpy states for multibranch jobs

### PR DESCRIPTION
**Pull request by imeredith**
# Description

See [JENKINS-40627](https://issues.jenkins-ci.org/browse/JENKINS-40627).

PR: https://github.com/jenkinsci/blueocean-plugin/pull/782
# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
@imeredith still relevant?

**Comment by michaelneale** [comment]
ping

**Comment by scherler** [comment]
I actually wonder why do you not use https://github.com/jenkinsci/blueocean-acceptance-test/blob/5fbc4742c3ab266cc324d2eb5d5a1825b15e88da/src/main/js/page_objects/blueocean/bluePipelineActivity.js?

**Comment by michaelneale** [comment]
yes I don't think this is testing anything new. Those empty states are changing anyway - so can probably close this.

**Comment by michaelneale** [comment]
old and empty states have changed now

**Pull request closed without merging**
