### PR TITLE
Remove blueocean runtime dependencies

### PR DESCRIPTION
**Pull request by vivek**
# Description

Removes dependency on workflow-aggregator plugin. It was needed only because some tests were testing stage view UI's div#pipeline-box element. It's not really needed, will be good to clean this up.

ATH passes https://ci.blueocean.io/blue/organizations/jenkins/ATH-Jenkinsfile/detail/remove-blueocean-runtime-dependencies/4/pipeline.

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
right - I guess this may slightly speed up tests too as we don't have to wait for that to load - fair to say?

**Comment by vivek** [comment]
yeah, does speeds up indeed.

**Comment by michaelneale** [comment]
:bee: if it works (which it seems to!). 

nice one.

**Comment by vivek** [comment]
ATH on CI and locally on my laptop works. @michaelneale you want to try out locally as well?

**Comment by michaelneale** [comment]
yes I will.

**Comment by michaelneale** [comment]
:bee: worked locally for me as well against master when I tried.

**Pull request merged**
