### PR TITLE
Bug/jenkins 39955 re run broken

### PR DESCRIPTION
**Pull request by michaelneale**
cc @kzantow test for https://github.com/jenkinsci/blueocean-plugin/pull/648

### CODE REVIEW

**Comment by kzantow** [comment]
@michaelneale I need to familiarize with ATH test better :( did you run this against my branch?

**Comment by michaelneale** [comment]
@kzantow only locally - but I am trying to verify also it fails on master. Happy to talk you through it. You can roll your own if you get familiar with it

**Comment by michaelneale** [comment]
@kzantow actually - my branch is rubbish. It doesn't fail against master, so it isn't testing for the right things it seems. Maybe worth having a crack at something that shows it up?

**Comment by kzantow** [comment]
@michaelneale happy to have the help on this one, plenty of other stuff to do

**Comment by michaelneale** [comment]
This doesn't fail correctly on master. Closing it.

**Comment by michaelneale** [comment]
ok, looks ok now

**Comment by michaelneale** [comment]
this passes on both master and keiths fork - so I propose we merge it to have re-run covered for pipeline jobs (that show up stage graph)

**Pull request merged**
