### PR TITLE
Jenkins 38068 Write documentation on AT with JSDOC and export the result

### PR DESCRIPTION
**Pull request by scherler**
# Description
Write documentation on AT with JSDOC and export the result

See [JENKINS-38068](https://issues.jenkins-ci.org/browse/JENKINS-38068).

Result: 
https://scherler.github.io/blueocean-acceptance-test/docs/page_objects.module_bluePipelineRunDetails.html

# Submitter checklist
- [ ] Link to JIRA ticket in description, if appropriate.
- [ ] Change is code complete and matches issue description
- [ ] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [ ] Ran Acceptance Test Harness against PR changes.

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by tfennelly** [comment]
@scherler I don't think you meant to commit the generated docs to github, did you?

142,000 lines of changes.

I love this !!

**Comment by scherler** [comment]
@tfennelly to use https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/ out of the box I understood you would need a doc folder that is hosting the generated doc.

As soon the PR is merged in master we can activate the gh page for AT

**Comment by tfennelly** [comment]
@scherler why not do it the same way as we're already doing it for the jdl? i.e. keep less shit in the repo .... generate it all at build time to a `.gitignore`d folder and then push the contents of that folder to the `gh-pages` branch i.e. the `gh-pages` branch contains all the generated docs from the `master` branch.

The `/doc` approach to doing this is probably fine if you have a small few docs in there, but not if you have 30,000 lines of generated stuff.

**Comment by tfennelly** [comment]
🐝 🍻

**Pull request merged**
