### PR TITLE
[activateFolder] activate the test cases from folder.js that are not …

### PR DESCRIPTION
**Pull request by scherler**
# Description

activating all tests that can be run 

@jenkinsci/code-reviewers @reviewbybees 

…having the problem with multibranch create

### CODE REVIEW

**Comment by tfennelly** [comment]
🐝 thanks man ... I was about to do this (no joking)

I kicked off a build of it ... https://ci.blueocean.io/job/ATH-Jenkinsfile/job/activateFolder/

**Comment by scherler** [comment]
@tfennelly cheers mate

**Comment by scherler** [comment]
https://ci.blueocean.io/job/ATH-Jenkinsfile/job/activateFolder/2/ has thrown the siganture error so we cannot activate this tests.

**Comment by michaelneale** [comment]
THE SIGNATURE ERROR AGAIN FFS

**Comment by scherler** [comment]
@michaelneale @tfennelly one observation is that we do not use a path from within the docker instance. If the ```.git``` folder could not be found (e.g. for not being visible) I would expect that the repoPath is null. That raises the question why that is happening.

**Comment by tfennelly** [comment]
@scherler @michaelneale I'm looking at this.

**Comment by michaelneale** [comment]
nice - so we might be getting to the bottom of this evil thing

**Comment by scherler** [comment]
@tfennelly you may need https://github.com/jenkinsci/blueocean-acceptance-test/pull/57 to fix it

**Comment by tfennelly** [comment]
@scherler @michaelneale back looking at this today ... I had a number of issues with the folder test, but the signature one was tracked down to the fact that we needed to `git config` the user in the docker container. I'll create a PR onto this PR.

**Comment by tfennelly** [comment]
I was not able to create a PR onto this PR so I created a new PR. See https://github.com/jenkinsci/blueocean-acceptance-test/pull/59

**Comment by tfennelly** [comment]
Merged and continued in #59, which is now merged.

**Pull request closed without merging**
