### PR TITLE
Fixes for new JTable stuff

### PR DESCRIPTION
**Pull request by michaelneale**
# Description

Companion for the https://github.com/jenkinsci/blueocean-plugin/pull/885 PR

@reviewbybees

### CODE REVIEW

**Comment by michaelneale** [comment]
this passes now on that branch - it looks someone knew that "useXpath" mutates browser but not everyone... so I added in a bunch of additional flips back to the "default" just to be sure (may help wit rerunning, or be a noop... not sure, btu don't care. Really disappointed in nightwatch).

**Comment by sophistifunk** [comment]
🐝

**Comment by scherler** [comment]
I will not repeat that this xpath selectors should be in the page object, since you guys do not give a ....

**Comment by michaelneale** [comment]
@scherler there are no types in page objects - how does one tell if a string is an xpath or not? assume it is with `//` prefix and hope that the consumer uses it appropriately? can you put xpath strings in page object and refer to them with `@` like other things? 

This has to be xpath as there is no way to select on text content in css. And also, the api "useXpath" is just terrible (it changes the browser object to use xpath until you set it back). Basically this is all pretty awful code, doing things like this isn't really making the gaping wound of test code much neater.

**Comment by i386** [comment]
This repository has been retired. Please see the README.

**Pull request closed without merging**
