### PR TITLE
[JENKINS-40105_Enable_all_folder.js_test_cases] activate most of the …

### PR DESCRIPTION
**Pull request by scherler**
# Description

See [JENKINS-40105](https://issues.jenkins-ci.org/browse/JENKINS-40105).

# Submitter checklist
- [x] Link to JIRA ticket in description, if appropriate.
- [x] Change is code complete and matches issue description
- [x] Reviewer's manual test instructions provided in PR description. See Reviewer's first task below.
- [x] Ran Acceptance Test Harness against PR changes.

https://ci.blueocean.io/job/ATH-Jenkinsfile/job/JENKINS-40105_Enable_all_folder.js_test_cases/
cases 34 to 36

# Reviewer checklist
- [ ] Run the changes and verified the change matches the issue description
- [ ] Reviewed the code
- [ ] Verified that the appropriate tests have been written or valid explanation given

@jenkinsci/code-reviewers @reviewbybees 

…tests again. there had been some that are still failing need to be picked up again.

### CODE REVIEW

**Comment by michaelneale** [comment]
as long as this passes against blue ocean master then :bee:

**Comment by scherler** [comment]
@michaelneale I had to deactivate two different tests https://github.com/jenkinsci/blueocean-acceptance-test/pull/76/files#diff-8f00f9e2ef5b4b1e8cbd414177b61320R150 https://github.com/jenkinsci/blueocean-acceptance-test/pull/76/files#diff-8f00f9e2ef5b4b1e8cbd414177b61320R161 since they fail on ATH server but local not. Could you test whether they work for you local?

**Comment by michaelneale** [comment]
@scherler will do - sure.

**Comment by michaelneale** [comment]
I notice with that last commit it passes - @scherler sorry not clear what you want me to try on my machine - do you want me to checkout commit 8f00f9e2ef5b4b1e8cbd414177b61320R150 and see if it fails the way CI does? or before it?

**Comment by michaelneale** [comment]
tried this a few times and saw a differnet sort of failure: https://ci.blueocean.io/job/ATH-Jenkinsfile/job/JENKINS-40105_Enable_all_folder.js_test_cases/28/console

**Comment by scherler** [comment]
@michaelneale the last failure seems to be related to https://github.com/jenkinsci/blueocean-acceptance-test/pull/81 (which fixes that error). 

https://ci.blueocean.io/blue/organizations/jenkins/ATH-Jenkinsfile/detail/JENKINS-40105_Enable_all_folder.js_test_cases/28/pipeline#step-25-log-742 and 743 leads to https://github.com/jenkinsci/blueocean-acceptance-test/blob/master/src/main/js/api/sse.js#L88

**Comment by scherler** [comment]
@michaelneale 

In my local box at home the test worked fine when leaving 
https://github.com/jenkinsci/blueocean-acceptance-test/blob/JENKINS-40105_Enable_all_folder.js_test_cases/src/test/js/edgeCases/folder.js#L150

```
 //blueRunDetailPage.validateNotEmptyArtifacts(2); -> ATH is failing but local is not

```

and https://github.com/jenkinsci/blueocean-acceptance-test/blob/JENKINS-40105_Enable_all_folder.js_test_cases/src/test/js/edgeCases/folder.js#L161

```
//blueRunDetailPage.validateFailingTests(); -> ATH is failing but local is not
```

If you get the head version of this branch and just uncomment both lines in your local checkout, what happens? Does it fail like in ATH or does it pass?

I will try now with 2 other boxes to see whether I can reproduce the ATH failure on the validation of the tests.

**Comment by scherler** [comment]
@michaelneale https://ci.blueocean.io/blue/organizations/jenkins/ATH-Jenkinsfile/detail/JENKINS-40105_Enable_all_folder.js_test_cases/29/pipeline that has the other PR included now and seems to work fine

**Comment by scherler** [comment]
@michaelneale I think we found a regression with the ATH. :) I had to deactivate 
```
       //blueRunDetailPage.validateGraph(); // test whether we have a pipeline graph
       //blueRunDetailPage.validateSteps(); // validate that steps are displayed
```

since the multi-pipeline did not produce a pipelineGraph with 

```
node {
    stage 'Stage 1 - scm'
    echo 'Stage 1 - scm'
    checkout scm
    sleep 5
    stage 'Stage 2'
    stage 'Stage archiveArtifacts'
    archiveArtifacts 'TEST-*.xml'
    stage 'Stage test'
    sh 'touch *.xml'
    step([$class: 'JUnitResultArchiver', testResults: 'TEST-*.xml'])
}
```

When using block syntax I get the expected behaviour again.

I validated that the former syntax is producing the expected result https://ci.blueocean.io/blue/organizations/jenkins/folders%2Fsubfolder%2Fthirdfolder%2FhelloPipeline/detail/helloPipeline/4/pipeline/8 in "normal" pipeline script.

I created a small test rep to test and that works as well fine https://github.com/scherler/jenkinsMultiBranchOldSyntax 
https://ci.blueocean.io/blue/organizations/jenkins/folders%2Fsubfolder%2Fthirdfolder%2FoldSyntax/detail/master/1/pipeline 

It seems to be a problem of the ATH but only for blueocean:

screenshot from 2016-12-13 15-33-41
screenshot from 2016-12-13 15-33-21

It may be some version problems of the underlying plugins, for now I changed the `Jenkinsfile` to blockscope but we may want to revert that to determine what the problem is.

**Comment by scherler** [comment]
I had to de activate the stage/steps validation again, since it seems that ATH server does not like it and it is not generating the graphNode

**Comment by michaelneale** [comment]
@scherler so even with block scoped stages it isn't working correctly? 

For the non block scoped, could open a ticket with instructions for vivek to look at at some point. Do you want me to try something locally?

**Comment by michaelneale** [comment]
hrm.. I ran it locally, and uncommented those lines, and it passed for me too - when you ran on CI - did you run it a few times with those lines left in? There are no library deltas between ATH running locally and on CI - it runs from the same installation and versions.

**Comment by michaelneale** [comment]
:bee: as it is, as it improves coverage, if you want to merge

**Comment by scherler** [comment]
@michaelneale I wrote in the mailing list the error I can see on a headless (no-xserver) linux. Basically do `init 4` ssh to the box and startup the AT in dev mode. Connect to the instance I can see an error about encoding. The same test on my GNOME desktop box is working fine, no problems with the path. I opened https://issues.jenkins-ci.org/browse/JENKINS-40441

I will merge this PR now as is.

**Pull request merged**
